menu:
  主页: /
  归档: /archives
  关于: /about

widgets: 
- search
- category
- tag
- recent_posts
- contactme
- friends
- other
- weibo

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: false
  google: true
  pinterest: false

fancybox: true

google_analytics:
rss:
