categories: Categories
search: Search
tags: Tags
recent_posts: Recent Posts
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: Archives: %s
page: Page %d
more_link: Read More
friends: Friends
contactme: Contact Me
